# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2501, 1201)
        Form.setMinimumSize(QtCore.QSize(2500, 1200))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 2500, 1200))
        self.label.setMinimumSize(QtCore.QSize(2500, 1200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/Ex_Block_diagram.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.etcBtn = QtWidgets.QPushButton(Form)
        self.etcBtn.setGeometry(QtCore.QRect(270, 160, 71, 41))
        self.etcBtn.setStyleSheet("background:transparent;")
        self.etcBtn.setText("")
        self.etcBtn.setObjectName("etcBtn")
        self.tempSensorBtn = QtWidgets.QPushButton(Form)
        self.tempSensorBtn.setGeometry(QtCore.QRect(350, 160, 81, 41))
        self.tempSensorBtn.setStyleSheet("background:transparent;")
        self.tempSensorBtn.setText("")
        self.tempSensorBtn.setObjectName("tempSensorBtn")
        self.adcBtn = QtWidgets.QPushButton(Form)
        self.adcBtn.setGeometry(QtCore.QRect(440, 160, 91, 41))
        self.adcBtn.setStyleSheet("background:transparent;")
        self.adcBtn.setText("")
        self.adcBtn.setObjectName("adcBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import resource_rc
